services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    env_file:
      - ./auth-service/.env
    ports:
      - "8001:8000"
    volumes:
      - ./auth-service/database:/var/www/database
      - ./auth-service/storage:/var/www/storage
    networks:
      - microservices-network

  project-service:
    build: ./project-service
    container_name: project-service
    env_file:
      - ./project-service/.env
    ports:
      - "8002:8000"
    volumes:
      - ./project-service/database:/var/www/database
      - ./project-service/storage:/var/www/storage
    depends_on:
      - auth-service
    networks:
      - microservices-network

  gateway-frontend:
    build: ./gateway-frontend
    container_name: gateway-frontend
    env_file:
      - ./gateway-frontend/.env
    ports:
      - "8080:8000"
    volumes:
      - ./gateway-frontend/database:/var/www/database
      - ./gateway-frontend/storage:/var/www/storage
    depends_on:
      - auth-service
      - project-service
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
